name: Close Empty Lingohub Branch
run-name: ${{github.actor}} ran this workflow
on:
  workflow_dispatch: # to run this workflow manually
  #pull_request:
  #  types: [opened]
  pull_request_target: # needed for closing pull request (not just "pull_request")
    types: [opened]
    paths: # only runs when these files have changed / or not changed when prefixed with "!"
      #- 'src/main/typescript/i18n/de.json'
      #- '!src/main/typescript/i18n/de.json'
jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      all: ${{steps.changes.outputs.all}}
      json: ${{steps.changes.outputs.json}}
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
      - name: some-test-outputs
        run: | 
          echo ${{ github.head_ref }}
          echo ${{ github.sha }}
          echo ${ git diff ${{ github.head_ref }} ${{ github.base_ref}} }
      - name: get-changed-files
        id: changes
        run: |
          echo {all}={$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)} >> $GITHUB_OUTPUT
          echo "::set-output name=json::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .json$ | xargs)"
  echo-changed-files:
    runs-on: ubuntu-latest
    needs: changed-files
    # run only if there are changed files
    # if: ${{needs.changedfiles.outputs.ts}}
    steps:
      - name: echo-test-text
        run: echo "** This is just some test text **"
      - name: echo-all-changed-files
        run: echo ${{needs.changed-files.outputs.all}}
      - name: echo-json-changed-files
        run: echo ${{needs.changed-files.outputs.json}}
  close-pull-request:
    if: startsWith(github.head_ref, 'lingohub-')
    runs-on: ubuntu-latest
    steps:
      - name: 'Close pull request which triggered pull_request_target'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: 'Pull Request was automatically closed by the Github Action'
      - name: 'Send Message to Slack'
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "The Pull Request Branch name started with lingohub"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: 'Info message'
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Github Action Workflow ran"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
