name: a-first-workflow
run-name: ${{github.actor}} ran this workflow
on:
  pull_request:
    types:
      - opened
jobs:
  check-changes:
    run_if:
      if: startsWith(github.head_ref, 'lingohub')
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: echo "This was a Pull Request from Lingohub"
