name: Delete Lingohub Branch
run-name: ${{github.actor}} ran this workflow
on:
  pull_request:
    types: [opened]
jobs:
  delete-branch:
    run_if:
      if: startsWith(github.head_ref, 'lingohub')
    runs-on: ubuntu-latest
    steps:
      - name: 'Send Message to Slack'
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with: |
          {
            "text": "The Pull Request Branch name started with lingohub"
          }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
