name: Git Diff
run-name: Git Diff Workflow run by ${{github.actor}}
on:
  pull_request: # for get-diff-action
    types: [opened]
  pull_request_target: # for close-pull-request
    types: [opened]
jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
      - name: diff-action
        uses: technote-space/get-diff-action@v6
        with:
          FILES:
            de.json
      - name: de.json-was-changed
        if: env.MATCHED_FILES
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "The json file WAS CHANGED"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: de.json-was-not-changed
        if: env.GIT_DIFF && !env.MATCHED_FILES
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Github Action Workflow ran"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: close-pull-request
        if: startsWith(github.head_ref, 'lingohub-') && env.GIT_DIFF && !env.MATCHED_FILES
        uses: superbrothers/close-pull-request@v3
        with:
          comment: 'Pull Request was automatically closed by the Github Action'
      - name: close-pull-request-slack-message
        if: startsWith(github.head_ref, 'lingohub-') && env.GIT_DIFF && !env.MATCHED_FILES
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "The Pull Request Branch name started with lingohub, was empty and was closed"  
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}