name: Issue Assignment
on:
  issues:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Auto assign issue'
        #uses: pozil/auto-assign-issue@v1.11.0
        uses: wow-actions/auto-assign@v2
        with:
          #repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: didldot
      - name: 'Send Slack Message'
        run: |
          curl -X POST -H 'Content-type: application/json' -H 'Authorization: Bearer xoxb-4672982336497-4673164031713-vXDRjk9jwLi7CnEBkO6hFnKx' --data '{"channel": "C04JZPWKT5M","text": "Hello from curl, :tada:"}' https://slack.com/api/chat.postMessage