name: Issue Assignment
on:
  issues:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto assign issue'
        uses: pozil/auto-assign-issue@v1.0.3
        with:
          node-version: '16'
          repo-token: ${{ secrets.GITHUB.TOKEN }}
          assignees: didldot