name: Issue Assignment
on:
  issues:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Auto assign issue'
        #uses: pozil/auto-assign-issue@v1.11.0
        uses: wow-actions/auto-assign@v2
        with:
          #repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: somebody