name: Issue Assignment
on:
  issues:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Auto assign issue'
        #uses: pozil/auto-assign-issue@v1.11.0
        uses: wow-actions/auto-assign@v2
        with:
          #repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: didldot
      - name: 'Send Slack Message'
        #run: |
        #  curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello Github Webhook!"}' https://hooks.slack.com/services/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
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "key": "value",
              "foo": "bar"
            }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}